AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
        password:
            type: string
            length: 11
        email:
            type: text
            length: 200
        isActive:
            type: boolean