# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        projector_provider:
            entity:
                class: Appbundle\Entity\user
                property: username
        # in_memory:
        #     memory:
        #         users:
        #             jon:
        #                 password: pword
        #                 roles: 'ROLE_ADMIN'
        #             kfc:
        #                 password: chicken
        #                 roles: 'ROLE_USER'


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        
       
        default:
            security: true
            provider: projector_provider 
            anonymous: ~
            pattern: .*
            form_login:
                login_path: /projector/login
                check_path: /projector/login_check
                always_use_default_target_path: true
                default_target_path: /projector/projects
            logout:
                path: /logout
                invalidate_session: true
            
           
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/projects, roles: ROLE_USER }
